language: node_js
before_script:
  - sleep 15
os:
  - linux
  - osx
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - iojs
services:
  - mongodb
env:
  - secure: kqVQUEX1GAvpFzb3UQNIySTUPFAp9zQ0s9Riuzty2sll/P2rJgS6rW8aWs6rgMg7AwmLNRqCxiKuWi82eaVTn0nBX2Pt3VPKlbyKi6luCFsEO1KUB/hk98nneLsSCnVo5aYJsg2248YUTvY+ZC716xI+IuWOYfuUAVmrv8WtR7s=
after_success: npm run codeclimate
